### PR TITLE
remove section runtime debugging

### PR DESCRIPTION
**Pull request by raorao**
instead, reference difficulty of updating nested data structures.

fixes:  https://github.com/elmbridge/curriculum/issues/37

### CODE REVIEW

**Comment by raorao** [comment]
solving conflicts

**Comment by avh4** [comment]
Seems fine to me.  You don't think it's important to include something about how the debugging experience will be different?

**Comment by raorao** [comment]
I think we can leave it off for now. I've been trying to formulate a point about how functional languages don't have the same conventions around debugging tools that OO languages do, but I can't seem to find the words. Worth punting on IMO.

**Comment by raorao** [comment]
merging.

**Pull request merged**
